package hibernatehql;
// Generated 08-feb-2023 19:39:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ciclo generated by hbm2java
 */
public class Ciclo  implements java.io.Serializable {


     private String codCiclo;
     private String nombre;
     private String grado;
     private Set modulos = new HashSet(0);

    public Ciclo() {
    }

	
    public Ciclo(String codCiclo, String nombre, String grado) {
        this.codCiclo = codCiclo;
        this.nombre = nombre;
        this.grado = grado;
    }
    public Ciclo(String codCiclo, String nombre, String grado, Set modulos) {
       this.codCiclo = codCiclo;
       this.nombre = nombre;
       this.grado = grado;
       this.modulos = modulos;
    }
   
    public String getCodCiclo() {
        return this.codCiclo;
    }
    
    public void setCodCiclo(String codCiclo) {
        this.codCiclo = codCiclo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getGrado() {
        return this.grado;
    }
    
    public void setGrado(String grado) {
        this.grado = grado;
    }
    public Set getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Set modulos) {
        this.modulos = modulos;
    }




}


