package hibernate2;
// Generated 25-ene-2023 19:59:29 by Hibernate Tools 4.3.1



/**
 * AlumnoModuloId generated by hbm2java
 */
public class AlumnoModuloId  implements java.io.Serializable {


     private String codAlumno;
     private String codModulo;

    public AlumnoModuloId() {
    }

    public AlumnoModuloId(String codAlumno, String codModulo) {
       this.codAlumno = codAlumno;
       this.codModulo = codModulo;
    }
   
    public String getCodAlumno() {
        return this.codAlumno;
    }
    
    public void setCodAlumno(String codAlumno) {
        this.codAlumno = codAlumno;
    }
    public String getCodModulo() {
        return this.codModulo;
    }
    
    public void setCodModulo(String codModulo) {
        this.codModulo = codModulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlumnoModuloId) ) return false;
		 AlumnoModuloId castOther = ( AlumnoModuloId ) other; 
         
		 return ( (this.getCodAlumno()==castOther.getCodAlumno()) || ( this.getCodAlumno()!=null && castOther.getCodAlumno()!=null && this.getCodAlumno().equals(castOther.getCodAlumno()) ) )
 && ( (this.getCodModulo()==castOther.getCodModulo()) || ( this.getCodModulo()!=null && castOther.getCodModulo()!=null && this.getCodModulo().equals(castOther.getCodModulo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodAlumno() == null ? 0 : this.getCodAlumno().hashCode() );
         result = 37 * result + ( getCodModulo() == null ? 0 : this.getCodModulo().hashCode() );
         return result;
   }   


}


